- name: Configure EC2 Deployment Server
  hosts: frontend
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required system dependencies
      apt:
        name: 
          - curl
          - unzip
          - python3-pip
          - docker.io
        state: present

    - name: Ensure AWS CLI is installed
      command: aws --version
      register: aws_cli_check
      ignore_errors: yes

    - name: Install AWS CLI if missing
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      args:
        creates: /usr/local/bin/aws
      when: aws_cli_check.rc != 0

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Set AWS Credentials for ECR Login
      shell: |
        export AWS_SHARED_CREDENTIALS_FILE=/home/ubuntu/.aws/credentials
        export AWS_CONFIG_FILE=/home/ubuntu/.aws/config
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 314146332315.dkr.ecr.us-east-1.amazonaws.com
      register: ecr_login
      retries: 3
      delay: 5
      ignore_errors: yes

    - name: Debug AWS ECR Login Output
      debug:
        msg: "{{ ecr_login.stdout }}"

    - name: Stop and remove existing container (if running)
      shell: |
        docker stop househunt || true
        docker rm househunt || true
      ignore_errors: yes

    - name: Pull the latest Docker image from AWS ECR
      shell: |
        docker pull 314146332315.dkr.ecr.us-east-1.amazonaws.com/househunt:latest

    - name: Run the Docker container
      shell: |
        docker run -d --name househunt -p 80:80 314146332315.dkr.ecr.us-east-1.amazonaws.com/househunt:latest