- name: Configure EC2 Deployment Server
  hosts: frontend
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required system dependencies
      apt:
        name: 
          - curl
          - unzip
          - python3-pip
          - docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Authenticate AWS ECR as Ubuntu User
      become: no  # Run this command as the Ubuntu user, not root
      shell: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
      register: ecr_login
      retries: 3
      delay: 5
      until: ecr_login.rc == 0
      ignore_errors: no

    - name: Debug AWS ECR Login Output
      debug:
        msg: "{{ ecr_login.stdout }}"

    - name: Ensure Docker image version file exists
      stat:
        path: /var/jenkins_home/workspace/docker_image_version.txt
      register: docker_image_file

    - name: Get the latest Docker image version from Jenkins
      shell: cat /var/jenkins_home/workspace/docker_image_version.txt
      register: docker_image
      when: docker_image_file.stat.exists
      ignore_errors: yes

    - name: Debug Docker Image Version
      debug:
        msg: "Docker Image: {{ docker_image.stdout }}"
      when: docker_image.stdout is defined and docker_image.stdout | length > 0

    - name: Stop and remove existing container (if running)
      shell: |
        docker stop househunt || true
        docker rm househunt || true
      ignore_errors: yes

    - name: Pull the latest Docker image from AWS ECR
      shell: |
        docker pull {{ docker_image.stdout }}
      when: docker_image.stdout is defined and docker_image.stdout | length > 0

    - name: Run the Docker container
      shell: |
        docker run -d --name househunt -p 80:80 {{ docker_image.stdout }}
      when: docker_image.stdout is defined and docker_image.stdout | length > 0